# Generated by Django 5.1.4 on 2025-01-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_bonus_amount_customuser_referral_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
