# Generated by Django 5.1.4 on 2025-01-31 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_giftcardtransaction_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airtimerequest',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='datarequest',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
