# Generated by Django 5.1.4 on 2025-02-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_phone_number_airtimerequest_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricityrequest',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
