# Generated by Django 5.1.4 on 2025-01-12 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
