# Generated by Django 5.1.4 on 2025-02-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_giftcardcurrency_giftcarddenomination_giftcardtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcarddenomination',
            name='value',
            field=models.CharField(max_length=20),
        ),
    ]
