# Generated by Django 5.1.4 on 2025-02-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_giftcardrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardrate',
            name='rate',
            field=models.CharField(max_length=20),
        ),
    ]
