# Generated by Django 5.1.4 on 2025-01-16 15:36

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='service',
            field=models.CharField(choices=[('giftcard', 'Giftcard Purchase'), ('bill_payment', 'Bill Payment'), ('money_transfer', 'Money Transfer'), ('signup_bonus', 'Signup Bonus'), ('airtime', 'Airtime Purchase')], max_length=50),
        ),
        migrations.CreateModel(
            name='AirtimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('network', models.CharField(choices=[('mtn', 'MTN'), ('airtel', 'Airtel'), ('glo', 'Glo'), ('9mobile', '9mobile')], max_length=10)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='airtime_request', to='app.transaction')),
            ],
        ),
    ]
