# Generated by Django 5.1.4 on 2025-01-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_transaction_service_airtimerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtimerequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
