# Generated by Django 5.1.4 on 2025-01-17 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_datarequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='service',
            field=models.CharField(choices=[('giftcard', 'Giftcard Purchase'), ('bill_payment', 'Bill Payment'), ('money_transfer', 'Money Transfer'), ('signup_bonus', 'Signup Bonus'), ('airtime', 'Airtime Purchase'), ('data', 'Data Purchase'), ('cable', 'Cable TV')], max_length=50),
        ),
        migrations.CreateModel(
            name='CableRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('dstv', 'DSTV'), ('gotv', 'GOtv'), ('startimes', 'StarTimes')], max_length=20)),
                ('smart_card_number', models.CharField(max_length=20)),
                ('package', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cable_request', to='app.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('ekedc', 'EKEDC'), ('ikedc', 'IKEDC'), ('aedc', 'AEDC')], max_length=10)),
                ('meter_number', models.CharField(max_length=50)),
                ('plan', models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid')], max_length=10)),
                ('account_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Electricity Request',
                'verbose_name_plural': 'Electricity Requests',
            },
        ),
    ]
