# Generated by Django 5.1.4 on 2025-01-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_transaction_service_cablerequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='service',
            field=models.CharField(choices=[('giftcard', 'Giftcard Purchase'), ('bill_payment', 'Bill Payment'), ('money_transfer', 'Money Transfer'), ('signup_bonus', 'Signup Bonus'), ('airtime', 'Airtime Purchase'), ('data', 'Data Purchase'), ('cable', 'Cable TV'), ('electricity', 'Electricity Bill')], max_length=50),
        ),
    ]
