# Generated by Django 5.1.4 on 2025-01-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_transaction_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricityrequest',
            name='user',
        ),
    ]
