# Generated by Django 5.1.4 on 2025-01-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_electricityrequest_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricityrequest',
            options={},
        ),
    ]
