# Generated by Django 5.1.4 on 2025-01-17 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_electricityrequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricityrequest',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electricity_request', to='app.transaction'),
        ),
    ]
