# Generated by Django 5.1.4 on 2025-01-17 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_electricityrequest_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giftcard_name', models.CharField(max_length=100)),
                ('currency', models.CharField(choices=[('us', '🇺🇸 United States'), ('gb', '🇬🇧 United Kingdom'), ('ca', '🇨🇦 Canada')], max_length=2)),
                ('card_type', models.CharField(choices=[('ecode', 'E-code'), ('physical', 'Physical')], max_length=10)),
                ('denomination', models.CharField(choices=[('$25', '$25'), ('$50', '$50'), ('$100', '$100')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='giftcard_transaction', to='app.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='giftcard_images/')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.giftcardtransaction')),
            ],
        ),
    ]
