# Generated by Django 5.1.4 on 2025-01-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_giftcardtransaction_giftcardimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardtransaction',
            name='denomination',
            field=models.CharField(max_length=10),
        ),
    ]
