# Generated by Django 5.1.4 on 2025-01-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_giftcardtransaction_denomination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcardtransaction',
            name='user',
        ),
    ]
